name: ci

on: [push, pull_request]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        include:
          - os: ubuntu-22.04
            build_type: Release
            compiler: g++-10
            cxx_std: 17
          - os: ubuntu-24.04
            build_type: Release
            compiler: g++-12
            cxx_std: 20
          - os: ubuntu-24.04
            build_type: Release
            compiler: g++-14
            cxx_std: 23

          - os: ubuntu-22.04
            build_type: Release
            compiler: clang++-13
            cxx_std: 17
          - os: ubuntu-24.04
            build_type: Release
            compiler: clang++-16
            cxx_std: 20
          - os: ubuntu-24.04
            build_type: Release
            compiler: clang++-18
            cxx_std: 23

          - os: windows-2022
            build_type: Release
            generator: Visual Studio 17 2022
            arch: Win32
          - os: windows-2022
            build_type: Release
            generator: Visual Studio 17 2022
            arch: x64

          - os: windows-2022
            build_type: Release
            generator: MinGW Makefiles

    steps:
      - uses: actions/checkout@v3

      - name: configure-ubuntu
        if: ${{ contains(matrix.os, 'ubuntu') }}
        run: >
          cmake
          -DCMAKE_CXX_COMPILER=${{ matrix.compiler }}
          -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}
          -DVT_CXX_STD=${{ matrix.cxx_std }}
          -B ${{ github.workspace }}/build
          -S ${{ github.workspace }}

      - name: configure-vs
        if: ${{ contains(matrix.generator, 'Visual Studio') }}
        run: >
          cmake
          -G "${{ matrix.generator }}"
          -A ${{ matrix.arch }}
          -B ${{ github.workspace }}/build
          -S ${{ github.workspace }}

      - name: configure-mingw
        if: ${{ contains(matrix.generator, 'MinGW') }}
        run: >
          cmake
          -G "${{ matrix.generator }}"
          -DCMAKE_CXX_COMPILER=g++
          -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}
          -B ${{ github.workspace }}/build
          -S ${{ github.workspace }}

      - name: build
        run: >
          cmake
          --build ${{ github.workspace }}/build
          --config ${{ matrix.build_type }}

      - name: test-ubuntu
        if: ${{ contains(matrix.os, 'ubuntu') }}
        working-directory: ${{ github.workspace }}/build
        run: ./vt-threadpool-test

      - name: test-vs
        if: ${{ contains(matrix.generator, 'Visual Studio') }}
        shell: cmd
        working-directory: ${{ github.workspace }}/build/${{ matrix.build_type }}
        run: vt-threadpool-test.exe

      - name: test-mingw
        if: ${{ contains(matrix.generator, 'MinGW') }}
        shell: cmd
        working-directory: ${{ github.workspace }}/build
        run: vt-threadpool-test.exe
